<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\Socie\source\repos\Gw2Giveaway\Gw2Giveaway\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\2026-02-01-23.00-02-Gw2-64.png" />
    <None Remove="Images\Gold_coin.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\2026-02-01-23.00-02-Gw2-64.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Gold_coin.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\Socie\source\repos\Gw2Giveaway\Gw2Giveaway\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
