<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
	  <Version>1.0.7</Version>
	  <AssemblyVersion>1.0.6.0</AssemblyVersion>
	  <FileVersion>1.0.7.0</FileVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>gw2giveAwayIco.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\Socie\source\repos\Gw2Giveaway\Gw2Giveaway\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\2026-02-01-23.00-02-Gw2-64.png" />
    <None Remove="Images\Gold_coin.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="gw2giveAwayIco.ico" />
    <Content Include="Images\2026-02-01-23.00-02-Gw2-64.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Gold_coin.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\Socie\source\repos\Gw2Giveaway\Gw2Giveaway\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3296.44" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2.3" />
    <PackageReference Include="TwitchLib.Api" Version="3.10.2" />
    <PackageReference Include="TwitchLib.Client" Version="4.0.1" />
    <PackageReference Include="TwitchLib.EventSub.Websockets" Version="0.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
